import './globals.css'
import {Poppins} from "next/font/google"
import { ClerkProvider } from '@clerk/nextjs'
import Header from '../components/Header'


export const metadata = {
  title: 'Calamity Clerk',
  description: 'Generated by create next app',
}

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  style: ["normal", "italic"]
})

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      
    <html lang="en">
      <body className={poppins.className}>
      <Header/>
        <main className="conatiner mx-auto">
          <div className="flex items-start justify-center min-h-screen">
            <div className="mt-20">
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>

    </ClerkProvider>
  )
}
